### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by walro** [twingly/ruby-auth0#1]
VCR is probably suitable.

https://relishapp.com/vcr/vcr/docs
https://relishapp.com/vcr/vcr/v/2-9-2/docs/hooks/before-record-hook

**Comment by dentarg** [comment]
There is a pending PR, https://github.com/auth0/ruby-auth0/pull/9 that has tests.

**Comment by dentarg** [comment]
That PR has now been merged. If we contribute impersonation we can switch to using the official client.

**Comment by jage** [comment]
:+1:

**Comment by dentarg** [comment]
The official gem now has tests and integration tests (not complete, but something we can contribute to if we want). Closing this issue.
